name: Node.js CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: SetU up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check for leaked secrets
        uses: zricethezav/gitleaks-action@v1.6.0

      - name: Compile and lint
        run: pnpm run lint && pnpm run build

      - name: Run Tests
        id: run_tests
        run: |
          if pnpm test; then
            echo "Tests passed successfully" > test_results.md
            echo "::set-output name=result::$(cat test_results.md)"
          else
            echo "Tests failed" > test_results.md
            echo "::set-output name=result::$(cat test_results.md)"
            exit 1
          fi
        env:
          CI: true
